#!/usr/bin/env ansible-playbook
## vim:ft=ansible :

---

- debug: msg="==> Setting  PHP7 configure"

- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^listen.owner' line='listen.owner = {{ php_owner }}'"

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^listen.group' line='listen.group = {{ php_group}}'"

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php/7.0/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php7-fpm

- name: Ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php/7.0/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ php_timezone }}'

- name: Set up php.ini
  template:
    src: php.ini
    dest: /etc/php/7.0/fpm/
    owner: root
    group: root
    mode: 644
  notify: restart php7-fpm

# vim:ft=ansible :
