#!/usr/bin/env ansible-playbook
# ============================================================
#  Author: Chu-Siang Lai / chusiang (at) drx.tw
#  Blog: http://note.drx.tw
#  Filename: use-yum.yml
#  Modified: 2018-04-14 23:14
#  Description: Setup PHP7 on CentOS 6, 7.
#  Reference:
#
#   * How To Upgrade to PHP 7 on CentOS 7 | DigitalOcean
#    - https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-centos-7
#
# ============================================================
---

# before install.
- name: install requires package for use yum module
  become: true
  yum:
    name: libselinux-python
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Install epel from remote repo on CentOS 6
  become: true
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present
  when: ansible_distribution_major_version == "6"

- name: Install remi from remote repo on CentOS 6
  become: true
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-6.rpm
    state: present
  when: ansible_distribution_major_version == "6"

- name: Install epel from remote repo on CentOS 7
  become: true
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_distribution_major_version == "7"

- name: Install remi from remote repo on CentOS 7
  become: true
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  when: ansible_distribution_major_version == "7"

- name: get ius repo install script
  get_url:
    url: https://setup.ius.io/
    dest: /tmp/setup-ius.sh

- name: Install ius from remote repo
  become: true
  command: bash /tmp/setup-ius.sh

# Upgrade all packages.
- name: upgrade all packages
  become: true
  yum:
    name: "*"
    state: latest

# Install PHP7 packages.
- name: Install PHP Packages
  become: true
  yum:
    name: "{{ item }}"
    enablerepo: ius
    state: present
  with_nested: "{{ yum_php_packages }}"
  when: yum_php_packages is defined
  notify: restart php7-fpm on centos

# vim: ft=ansible :
